# Generated by Django 2.2.4 on 2019-08-31 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=30, null=True, verbose_name='著者')),
                ('genre', models.CharField(max_length=30, null=True, verbose_name='ジャンル')),
                ('summary', models.CharField(max_length=800, verbose_name='要約')),
                ('impressions', models.CharField(max_length=800, verbose_name='感想')),
                ('learn', models.CharField(max_length=800, verbose_name='学び')),
                ('story', models.CharField(max_length=800, verbose_name='進め方')),
                ('difference', models.CharField(max_length=800, verbose_name='違い')),
                ('importance', models.CharField(max_length=800, verbose_name='重要な文')),
                ('agree', models.CharField(max_length=800, verbose_name='賛成')),
                ('opposition', models.CharField(max_length=800, verbose_name='反対')),
                ('unkown', models.CharField(max_length=800, verbose_name='不明点')),
                ('example', models.CharField(max_length=800, verbose_name='事例')),
                ('inspiration', models.CharField(max_length=800, verbose_name='感銘')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
