# Generated by Django 2.2.4 on 2019-09-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20190916_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='images/', verbose_name='画像', width_field='url_width'),
        ),
        migrations.AddField(
            model_name='record',
            name='url_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='url_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
